Repository tomochain/infrastructure, pull requests merged in 2018-09, with the labels that each got.

#57 Remove infra docker images for devnet
  networks/devnet/earth/01bootnode.yml
  networks/devnet/earth/02masternodes.yml
  networks/devnet/main/01metrics.yml
  networks/devnet/main/02apps.yml
  networks/devnet/main/03proxy.yml
  networks/devnet/main/config.json
  networks/devnet/main/nginx.conf
  networks/devnet/moon/01bootnode.yml
  networks/devnet/moon/02masternodes.yml
  networks/devnet/sun/01bootnode.yml
  networks/devnet/sun/02masternodes.yml
Labels: docker, review

#59 fix alert with localhost url in testnet
  networks/testnet/main/01metrics.yml
Labels: review

#60 tomoscan add recaptcha
  .gitignore
  networks/devnet/main/02apps.yml
  networks/devnet/main/init.sh
  networks/testnet/main/02apps.yml
  networks/testnet/main/init.sh
Labels: review

#62 Split apps yml file into app specific ones
  networks/devnet/main/02netstats.yml
  networks/devnet/main/03tomomaster.yml
  networks/devnet/main/04tomoscan.yml
  networks/devnet/main/05proxy.yml
  networks/testnet/README.md
  networks/testnet/main/02netstats.yml
  networks/testnet/main/03tomomaster.yml
  networks/testnet/main/04tomoscan.yml
  networks/testnet/main/05faucet.yml
  networks/testnet/main/06proxy.yml
Labels: review

#63 Use testnet release channel in testnet
  networks/testnet/candidates/01fullnode.yml
  networks/testnet/earth/01bootnode.yml
  networks/testnet/earth/02masternodes.yml
  networks/testnet/main/01metrics.yml
  networks/testnet/main/02netstats.yml
  networks/testnet/main/03tomomaster.yml
  networks/testnet/main/04tomoscan.yml
  networks/testnet/main/05faucet.yml
  networks/testnet/main/06proxy.yml
  networks/testnet/moon/01bootnode.yml
  networks/testnet/moon/02masternodes.yml
  networks/testnet/sun/01bootnode.yml
  networks/testnet/sun/02masternodes.yml
Labels: pipeline, review

#65 Set node verbosity via env
  networks/devnet/earth/02masternodes.yml
  networks/devnet/moon/02masternodes.yml
  networks/devnet/sun/02masternodes.yml
  networks/testnet/candidates/01fullnode.yml
  networks/testnet/earth/02masternodes.yml
  networks/testnet/moon/02masternodes.yml
  networks/testnet/sun/02masternodes.yml
Labels: docker, enhancement, review
