Repository tomochain/infrastructure, pull requests merged in 2018-10, with the labels that each got.

#69 Add persistence to redis in testnet
  networks/testnet/main/03tomomaster.yml
  networks/testnet/main/04tomoscan.yml
Labels: enhancement, review

#71 Add slack webhook url to tomoscan server
  networks/testnet/main/04tomoscan.yml
  networks/testnet/main/init.sh
Labels: swarm

#75 Add tomoscan_txs
  networks/devnet/main/04tomoscan.yml
Labels: review

#78 Add centralized logging to devnet
  docker/graylog/Dockerfile
  docker/graylog/entrypoint.sh
  docker/graylog/plugins/.gitkeep
  networks/devnet/earth/02masternodes.yml
  networks/devnet/logging/01logging.yml
  networks/devnet/logging/05proxy.yml
  networks/devnet/logging/init.sh
  networks/devnet/logging/nginx.conf
  networks/devnet/moon/02masternodes.yml
  networks/devnet/sun/02masternodes.yml
  networks/testnet/candidates/01fullnode.yml
  networks/testnet/earth/02masternodes.yml
  networks/testnet/moon/02masternodes.yml
  networks/testnet/sun/02masternodes.yml
Labels: review

#80 add crawl reward container
  networks/devnet/main/03tomomaster.yml
  networks/testnet/main/03tomomaster.yml
Labels: review

#86 Change masternodes to stable version to keep devnet stable
  networks/devnet/earth/02masternodes.yml
  networks/devnet/moon/02masternodes.yml
  networks/devnet/sun/02masternodes.yml
Labels: review

#85 Remove reward services, make TomoMaster more simple
  networks/devnet/main/03tomomaster.yml
  networks/testnet/main/03tomomaster.yml
Labels: review
